Delete single codes in timezone
Because of:
Traceback (most recent call last):
  File "/app/main.py", line 136, in <module>
    TZ = timezone(os.environ.get("TZ", "America/New_York"))
  File "/usr/local/lib/python3.10/dist-packages/pytz/__init__.py", line 188, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: "'America/New_York'"

when running docker run -it --env-file ./.env --restart unless-stopped --name bing-rewards nelsondane/bing-rewards:latest